# Main composition file for Factorio Blueprints Decompress.
# Author: Arthur Cadore M. Barcella

version: '3.8'
services:
  blueprint:
    container_name: blueprint
    volumes:
      - "./data:/app/data/"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      INPUT_FILE: /
      OUTPUT_FILE: /arquivo-de-saida